"""
generate_artifact.py

Turns high-confidence proposals from the compound-learnings analyzer
into actual draft files (safe by default).

Philosophy:
- Never blindly overwrite production personas or rules.
- Always write to ~/.grok/skills-drafts/ first.
- Produce clear, reviewable diffs/patches.
- Support both "persona constraint" and "new rule" generation.
"""

from __future__ import annotations

import difflib
import os
from datetime import datetime
from pathlib import Path
from typing import Any

DRAFTS_DIR = Path.home() / ".grok" / "skills-drafts" / "compound-learnings"
PERSONAS_DIR = Path.home() / ".grok" / "bundled" / "skills" / "shared" / "personas"


def ensure_drafts_dir() -> Path:
    DRAFTS_DIR.mkdir(parents=True, exist_ok=True)
    return DRAFTS_DIR


def _show_unified_diff(original: str, proposed_addition: str, target_path: Path) -> None:
    """Show a clean unified diff for the planned change."""
    original_lines = original.splitlines(keepends=True)
    new_content = original.rstrip() + "\n\n" + proposed_addition.strip() + "\n"
    new_lines = new_content.splitlines(keepends=True)

    diff = difflib.unified_diff(
        original_lines,
        new_lines,
        fromfile=f"a/{target_path.name}",
        tofile=f"b/{target_path.name}",
        n=3,
    )

    print("\n" + "=" * 70)
    print(f"Planned change for: {target_path}")
    print("=" * 70)
    print("".join(diff))
    print("=" * 70)


def generate_persona_constraint(proposal: dict[str, Any], persona_name: str = "implementer") -> str:
    """
    Generate a well-formatted constraint block that can be added to a persona.
    """
    pattern = proposal["pattern"]
    rationale = proposal.get("rationale", "")
    draft_content = proposal.get("draft_content", "")

    timestamp = datetime.now().strftime("%Y-%m-%d")

    content = f"""# Proposed Constraint Addition
# Generated by compound-learnings on {timestamp}
# Pattern: {pattern}
# Impact: {proposal.get('impact', 'Unknown')} (Priority: {proposal.get('priority_score', 0)})

## Recommended addition to {persona_name}.md

Add the following under the "Non-Negotiable Constraints" section:

{draft_content}

## Rationale
{rationale}

## Suggested placement
Look for the existing "Non-Negotiable Constraints" or "Core Rules" section
and insert this as a new bullet or subsection.

## Review checklist before applying
- [ ] Does this overlap with existing constraints?
- [ ] Is the wording clear and not overly broad?
- [ ] Should this also be added to reviewer or security-auditor?
"""

    return content


def generate_rule_file(proposal: dict[str, Any]) -> str:
    """
    Generate a full rule file draft.
    """
    pattern = proposal["pattern"]
    category = proposal.get("category", "General")
    rationale = proposal.get("rationale", "")
    draft_content = proposal.get("draft_content", "")
    timestamp = datetime.now().strftime("%Y-%m-%d")

    safe_name = pattern.lower()
    safe_name = "".join(c if c.isalnum() or c in " -_" else "" for c in safe_name)
    safe_name = safe_name.replace(" ", "-").strip("-")[:60]

    content = f"""# {pattern}

> Generated by compound-learnings on {timestamp}
> Category: {category}
> Impact: {proposal.get('impact', 'Unknown')} | Priority: {proposal.get('priority_score', 0)}

## Pattern
{pattern}

## Why this matters
{rationale}

## Rule

{draft_content}

## Enforcement
- Add to the relevant persona (see related proposal)
- Consider adding to review checklists
- Consider adding to the `handoff` templates if this is a process issue

## Source
This rule was derived from recurring issues observed across multiple implementation runs.
"""

    return content, f"{safe_name}.md"


def write_draft(proposal: dict[str, Any], artifact_type: str = "auto") -> Path:
    """
    Write a draft artifact to the drafts directory.

    artifact_type: "persona", "rule", or "auto" (infers from proposal)
    """
    ensure_drafts_dir()

    rec_type = proposal.get("recommended_type", "").lower()

    if artifact_type == "auto":
        if "persona" in rec_type:
            artifact_type = "persona"
        elif "rule" in rec_type:
            artifact_type = "rule"
        else:
            artifact_type = "rule"  # default

    timestamp = datetime.now().strftime("%Y%m%d-%H%M")

    if artifact_type == "persona":
        persona = "implementer"
        content = generate_persona_constraint(proposal, persona)
        filename = f"{timestamp}-persona-{persona}-{proposal['pattern'][:40].replace(' ', '-')}.md"
        target = DRAFTS_DIR / filename

    else:
        content, rule_filename = generate_rule_file(proposal)
        filename = f"{timestamp}-{rule_filename}"
        target = DRAFTS_DIR / filename

    target.write_text(content, encoding="utf-8")
    return target


# ------------------------------------------------------------------
# Apply logic (careful, confirmation-based)
# ------------------------------------------------------------------

REAL_PERSONAS_DIR = Path.home() / ".grok" / "bundled" / "skills" / "shared" / "personas"
REAL_RULES_DIR = Path.home() / ".grok" / "rules"


def apply_draft(draft_path: Path, auto_confirm: bool = False) -> bool:
    """
    Apply a previously generated draft to the real system.

    Returns True if applied successfully.
    """
    if not draft_path.exists():
        print(f"Draft not found: {draft_path}")
        return False

    content = draft_path.read_text(encoding="utf-8")

    # Very simple heuristic to detect type
    is_persona = "Recommended addition to" in content and "persona" in content.lower()
    is_rule = content.strip().startswith("# ") and "Generated by compound-learnings" in content

    if is_persona:
        return _apply_persona_draft(draft_path, content, auto_confirm)
    elif is_rule:
        return _apply_rule_draft(draft_path, content, auto_confirm)
    else:
        print(f"Could not determine draft type for {draft_path.name}")
        return False


def _apply_persona_draft(draft_path: Path, content: str, auto_confirm: bool) -> bool:
    # Extract which persona from the draft
    persona_name = "implementer"
    if "reviewer" in draft_path.name.lower():
        persona_name = "reviewer"
    elif "security" in draft_path.name.lower():
        persona_name = "security-auditor"

    target_file = REAL_PERSONAS_DIR / f"{persona_name}.md"

    if not target_file.exists():
        print(f"Target persona file not found: {target_file}")
        return False

    # Extract the actual constraint text to insert
    # We look for the section after "## Recommended addition to"
    lines = content.splitlines()
    insert_lines = []
    in_insert = False
    for line in lines:
        if "Add the following under the" in line:
            in_insert = True
            continue
        if in_insert and line.startswith("##"):
            break
        if in_insert:
            insert_lines.append(line)

    proposed_text = "\n".join(insert_lines).strip()

    if not proposed_text:
        print("Could not extract content to insert from draft.")
        return False

    current_content = target_file.read_text(encoding="utf-8")

    # Show nice diff
    _show_unified_diff(current_content, proposed_text, target_file)

    if not auto_confirm:
        answer = input("\nApply this change? [y/N]: ").strip().lower()
        if answer not in ("y", "yes"):
            print("Skipped.")
            return False

    # Create backup
    backup_path = target_file.with_suffix(target_file.suffix + f".bak.{datetime.now().strftime('%Y%m%d-%H%M%S')}")
    backup_path.write_text(current_content, encoding="utf-8")
    print(f"Backup created: {backup_path}")

    # Apply
    new_content = current_content.rstrip() + "\n\n" + proposed_text + "\n"
    target_file.write_text(new_content, encoding="utf-8")

    print(f"Applied successfully to {target_file}")
    return True


def _apply_rule_draft(draft_path: Path, content: str, auto_confirm: bool) -> bool:
    # Extract rule title
    first_line = content.splitlines()[0]
    title = first_line.lstrip("# ").strip() if first_line.startswith("#") else draft_path.stem

    safe_filename = "".join(c if c.isalnum() or c in " -_" else "" for c in title).replace(" ", "-")[:80] + ".md"
    target_file = REAL_RULES_DIR / safe_filename

    REAL_RULES_DIR.mkdir(parents=True, exist_ok=True)

    print("\n" + "=" * 70)
    print(f"NEW FILE: {target_file}")
    print("=" * 70)
    print("\nThis will create a new rule file with the following content:\n")
    preview_lines = content.splitlines()[:25]
    print("\n".join(preview_lines))
    if len(content.splitlines()) > 25:
        print(f"\n... ({len(content.splitlines()) - 25} more lines)")

    if not auto_confirm:
        answer = input("\nCreate this new rule file? [y/N]: ").strip().lower()
        if answer not in ("y", "yes"):
            print("Skipped.")
            return False

    target_file.write_text(content, encoding="utf-8")
    print(f"Rule file created: {target_file}")
    return True


def main():
    """Simple CLI for testing generation."""
    import json
    import sys

    if len(sys.argv) < 2:
        print("Usage: python generate_artifact.py <proposal.json>")
        sys.exit(1)

    proposal_path = Path(sys.argv[1])
    proposal = json.loads(proposal_path.read_text(encoding="utf-8"))

    path = write_draft(proposal)
    print(f"Draft written to: {path}")


if __name__ == "__main__":
    main()